changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Added
      labels:
        - enhancement
        - docs
        - feat
    - title: Fixed
      labels:
        - fix
    - title: Other Changes
      labels:
        - refactor
        - chore
        - ci
        - test
